spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: apprnetinterface
        uri: lb://ApprNetInterface/
        predicates:
        - Path=/ApprNetInterface/**
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:1111/springboot/eureka/